Repository xun082/online-edit-web, pull requests merged in 2024-07, with the labels that each got.

#26 feat: 🚀 added unit testing capabilities
  .github/workflows/lint.yml
  eslint.config.cjs
  package.json
  pnpm-lock.yaml
  src/__tests__/Hello.test.tsx
  src/components/Hello.tsx
  tsconfig.json
  vitest.config.ts
  vitest.setup.ts
Labels: enhancement

#27 feat: 🚀 add Storybook
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/components/Button.stories.tsx
  src/components/button.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#28 feat: 🚀 add next-devtool
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
Labels: enhancement

#29 feat: 🚀 adding fetch warp
  .github/workflows/lint.yml
  eslint.config.cjs
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/services/request.ts
  src/utils/cn.ts
  src/utils/index.ts
  tsconfig.json
Labels: enhancement

#35 feat: init dashboard
  package.json
  pnpm-lock.yaml
  src/app/(main)/(router)/dashboard/page.tsx
  src/app/(main)/(router)/templates/page.tsx
  src/app/(main)/layout.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Avatar/index.tsx
  src/components/main/header/index.tsx
  src/components/main/sider/index.tsx
  src/components/ui/avatar/index.tsx
  src/components/ui/button/index.tsx
  tailwind.config.ts
Labels: enhancement

#36 feat: 🚀 initializes the editor page
  package.json
  pnpm-lock.yaml
  src/app/edit/page.tsx
  src/components/resize-handle/index.tsx
Labels: enhancement

#37 feat: 🚀 the edit page is rearranged and the preview component added
  package.json
  pnpm-lock.yaml
  src/app/edit/(main)/(router)/file/page.tsx
  src/app/edit/(main)/(router)/search/page.tsx
  src/app/edit/layout.tsx
  src/components/preview/index.tsx
  src/utils/constants.ts
  src/utils/index.ts
Labels: enhancement

#38 feat: init edit header
  pnpm-lock.yaml
  src/app/edit/layout.tsx
  src/app/page.tsx
  src/components/edit/header/index.tsx
  src/components/main/header/index.tsx
  src/components/main/sider/index.tsx
  src/utils/constants.ts
Labels: enhancement

#39 feat: 🚀 initializes the monaco editor editing function
  package.json
  pnpm-lock.yaml
  src/app/edit/layout.tsx
  src/components/editor/index.tsx
Labels: enhancement

#42 feat: 🚀 add community comments
  package.json
  src/app/community/page.tsx
Labels: enhancement

#43 fix: 🧩 use @giscus/react to configure and render the commenting system
  package.json
  pnpm-lock.yaml
  src/app/community/page.tsx
Labels: bug

#44 fix(contribution): fix the wrong address for upstream warehouse
  CONTRIBUTING-zh.md
  CONTRIBUTING.md
Labels: documentation

#45 style：Preview Component Style writing
  pnpm-lock.yaml
  src/app/edit/layout.tsx
  src/components/preview/booting/index.tsx
  src/components/preview/index.tsx
Labels: enhancement

#46 feat: init editor tabs and init split editor
  package.json
  pnpm-lock.yaml
  src/app/edit/layout.tsx
  src/components/edit/tabbar/index.tsx
  src/components/editor/index.tsx
  src/components/editor/utils.ts
  src/components/ui/dropdown-menu/index.tsx
  src/components/ui/scroll-area/index.tsx
  src/store/editorStore.tsx
Labels: enhancement

#47 fix: 🧩 fix vercel package build failed
  pnpm-lock.yaml
  src/app/edit/layout.tsx
  src/components/editor/index.tsx
  src/components/editor/utils.ts
Labels: bug

#48 feat: 🚀 initialize the ai page
  src/app/edit/(main)/(router)/ai/page.tsx
  src/app/edit/layout.tsx
  src/utils/constants.ts
Labels: enhancement

#51 chore: 🔨 update pnpm and node version requirements, reinstall depende…
  .github/workflows/lint.yml
  .npmrc
  package.json
  vercel.json
Labels: bug, enhancement

#52 featre：allow click to show flie and add scrolltoview for tabs
  .github/workflows/lint.yml
  src/app/edit/(main)/(router)/file/page.tsx
  src/components/edit/tabbar/index.tsx
  src/components/editor/index.tsx
  src/components/editor/utils.ts
Labels: enhancement

#53 featre: allow drag to show file
  package.json
  pnpm-lock.yaml
  src/app/edit/(main)/(router)/file/page.tsx
  src/app/edit/layout.tsx
  src/components/edit/tabbar/index.tsx
  src/components/editor/index.tsx
  src/components/file/fileItem/index.tsx
Labels: enhancement

#54 feat:add avatarPopover component
  package.json
  pnpm-lock.yaml
  src/components/avatarPopover/index.tsx
  src/components/avatarPopover/menu/index.tsx
  src/components/main/header/index.tsx
  tailwind.config.ts
Labels: enhancement

#57 feat:add avatarpopover to edit/file route
  src/components/edit/header/index.tsx
Labels: enhancement

#58 fix: drag bug and img loss
  src/components/edit/tabItem/index.tsx
  src/components/edit/tabbar/index.tsx
Labels: bug

#59 feat: init fileTree
  package.json
  pnpm-lock.yaml
  src/app/edit/(main)/(router)/file/page.tsx
  src/components/edit/tabItem/index.tsx
  src/components/edit/tabbar/index.tsx
  src/components/editor/index.tsx
  src/components/extension/tree-view-api/index.tsx
  src/components/file/fileItem/index.tsx
  src/components/file/fileTree/index.tsx
Labels: enhancement

#60 feat: 🚀 新增编辑页面 tab 栏切换动画
  src/app/edit/layout.tsx
Labels: enhancement

#62 feat: init upload file from local
  package.json
  pnpm-lock.yaml
  src/app/(main)/(router)/dashboard/page.tsx
  src/app/edit/(main)/(router)/file/page.tsx
  src/app/layout.tsx
  src/components/file/fileTree/index.tsx
  src/components/main/sider/index.tsx
  src/components/modals/create-project-modal/index.tsx
  src/components/provider/modal-provider/index.tsx
  src/components/ui/dialog/index.tsx
  src/hooks/useModal.ts
  src/store/uploadFileDataStore.tsx
  src/utils/getLocalDirectory.ts
Labels: enhancement

#65 feat: allow delete use file tree and allow keydowm to add
  src/components/extension/tree-view-api/index.tsx
  src/components/file/fileItem/index.tsx
  src/components/file/fileTree/index.tsx
  src/components/file/pendingFileItem/index.tsx
Labels: enhancement

#68 feat: 新增接入阿里云百炼模型 AI页面施工
  .env.development
  .env.production
  .gitignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/qwen.png
  src/app/edit/(main)/(router)/ai/page.tsx
  src/components/ai/chat/chat-bottombar.tsx
  src/components/ai/chat/chat-layout.tsx
  src/components/ai/chat/chat-list.tsx
  src/components/ai/chat/chat-topbar.tsx
  src/components/ai/chat/chat.tsx
  src/components/ai/chat/data.tsx
  src/components/ai/chat/textarea.tsx
  src/components/ai/chat/utils.ts
Labels: enhancement

#69 fix: 🧩 修复了 lock 文件缺少格式化而导致的大量 diff 变更
  next.config.mjs
  package.json
Labels: bug

#70 style: 🎨 代码优化
  src/app/not-found.tsx
  src/components/404/index.tsx
  src/components/ui/avatar/index.tsx
  src/components/ui/badge/index.tsx
  src/components/ui/button/index.tsx
  src/components/ui/dialog/index.tsx
  src/components/ui/dropdown-menu/index.tsx
Labels: documentation

#72 docs: 📚 添加 ui 组件文档
  src/components/ui/avatar/index.stories.tsx
  src/components/ui/badge/index.stories.tsx
  src/components/ui/button/index.stories.tsx
  src/components/ui/dialog/index.stories.tsx
  src/components/ui/dropdown-menu/index.stories.tsx
  src/components/ui/input/index.stories.tsx
  src/components/ui/scroll-area/index.stories.tsx
Labels: documentation

#77 fix: 🧩 修复了 prettier 每次格式化可能对 lock 文件造成大规模 diff 的问题
  .prettierignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
Labels: bug

#76 feat: 增加 settings 页面和修改 menu 组件
  package.json
  pnpm-lock.yaml
  src/app/edit/(main)/(router)/plugins/page.tsx
  src/app/edit/(main)/(router)/settings/page.tsx
  src/components/avatarPopover/index.tsx
  src/components/avatarPopover/menu/index.tsx
  src/components/menu/index.tsx
  src/components/ui/select/index.tsx
  src/components/ui/tooltip/index.tsx
Labels: enhancement

#78 chore: 🔨 improve code structure and add documentation
  src/app/edit/(main)/(router)/settings/page.tsx
  src/components/ui/select/index.stories.tsx
  src/components/ui/select/index.tsx
  src/components/ui/tooltip/index.stories.tsx
  src/components/ui/tooltip/index.tsx
Labels: documentation

#81 feat：添加webContainer
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/edit/header/index.tsx
  src/components/file/fileItem/index.tsx
  src/components/webContainerProvider/index.tsx
  src/store/uploadFileDataStore.tsx
  src/store/webContainerStore.tsx
  src/types/index.ts
  src/utils/constants.ts
  src/utils/getLocalDirectory.ts
  src/utils/index.ts
  src/utils/webcontainer.ts
  vercel.json
Labels: enhancement

#86 feat: 引入常见文件图标
  public/images/fileIcon/FileDir.svg
  public/images/fileIcon/JavaScript.svg
  public/images/fileIcon/css.svg
  public/images/fileIcon/eslint.svg
  public/images/fileIcon/git.svg
  public/images/fileIcon/html.svg
  public/images/fileIcon/image.svg
  public/images/fileIcon/json.svg
  public/images/fileIcon/jsx.svg
  public/images/fileIcon/less.svg
  public/images/fileIcon/markdown.svg
  public/images/fileIcon/prettier.svg
  public/images/fileIcon/scss.svg
  public/images/fileIcon/ts.svg
  public/images/fileIcon/vue.svg
  public/images/fileIcon/yaml.svg
  src/components/edit/tabItem/index.tsx
  src/components/file/fileItem/index.tsx
  src/utils/fileIconMap.ts
  src/utils/index.ts
Labels: enhancement

#87 feat/ preview
  next.config.mjs
  src/components/preview/index.tsx
  src/components/terminal/index.tsx
  src/store/webContainerStore.tsx
Labels: enhancement

#88 feat: 文件编辑后同步到webcontainer文件系统
  src/app/edit/(main)/(router)/file/page.tsx
  src/components/editor/index.tsx
  src/components/file/fileTree/index.tsx
  src/components/file/pendingFileItem/index.tsx
Labels: enhancement

#89 feat:删除文件时与webcontainer同步，初始化上传文件ui
  package.json
  pnpm-lock.yaml
  src/app/edit/(main)/(router)/file/page.tsx
  src/components/editor/index.tsx
  src/components/extension/tree-view-api/index.tsx
  src/components/file/fileItem/index.tsx
  src/components/file/fileTree/index.tsx
  src/components/modals/create-project-modal/index.tsx
  src/components/ui/command/index.tsx
  src/components/ui/tabs/index.tsx
  src/components/ui/textarea/index.tsx
  src/store/uploadFileDataStore.tsx
Labels: enhancement

#91 style: 🎨 优化首页代码
  src/app/page.tsx
Labels: documentation

#92 feat/基本实现文件树和webContainer的持久化
  src/app/(main)/(router)/dashboard/page.tsx
  src/app/edit/[projectId]/(main)/(router)/ai/page.tsx
  src/app/edit/[projectId]/(main)/(router)/file/page.tsx
  src/app/edit/[projectId]/(main)/(router)/plugins/page.tsx
  src/app/edit/[projectId]/(main)/(router)/search/page.tsx
  src/app/edit/[projectId]/(main)/(router)/settings/page.tsx
  src/app/edit/[projectId]/layout.tsx
  src/components/edit/header/index.tsx
  src/components/editor/index.tsx
  src/components/modals/create-project-modal/index.tsx
  src/components/preview/index.tsx
  src/components/webContainerProvider/index.tsx
  src/store/uploadFileDataStore.tsx
  src/store/webContainerStore.tsx
  src/utils/constants.ts
  src/utils/getLocalDirectory.ts
  src/utils/index.ts
  src/utils/time.ts
  src/utils/webcontainer.ts
Labels: enhancement
